# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eac8df82355de1cf14182aa1877e399aeb0855e73b790a1666b5e6e280d5c572eef31cb3e3c4f74c9b16771fdbb6ef0c9333ebf35b6afc426970abd3c1e6e2c4

test:
  secret_key_base: 33750aac5e98ae4b76d0052e7e64a396084c0f0fef54b51ace1153845cad967800c6f322b1f64d2d5ebb4afd20a0ebc7d830157894ec7f6ee9f6212d49e25bdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
